//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tier_1_WebUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptimizationTask
    {
        public string TaskID { get; set; }
        public string Name { get; set; }
        public string TaskType { get; set; }
        public string IssuedBy { get; set; }
        public Nullable<System.DateTime> IssuedOn { get; set; }
        public Nullable<System.DateTime> AllottedOn { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public string DoneBy { get; set; }
        public string InputValues { get; set; }
        public string OutputValues { get; set; }
        public string ReferenceValues { get; set; }
        public string Notes { get; set; }
        public string Logs { get; set; }
        public string TaskStaus { get; set; }
    
        public virtual LoginAccount LoginAccount { get; set; }
    }
}
