//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tier_3_Transport.TaskManager {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskDetails", Namespace="http://gams.com")]
    [System.SerializableAttribute()]
    public partial class TaskDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InputValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string InputValues {
            get {
                return this.InputValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.InputValuesField, value) != true)) {
                    this.InputValuesField = value;
                    this.RaisePropertyChanged("InputValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReferenceValues {
            get {
                return this.ReferenceValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceValuesField, value) != true)) {
                    this.ReferenceValuesField = value;
                    this.RaisePropertyChanged("ReferenceValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TaskID {
            get {
                return this.TaskIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskIDField, value) != true)) {
                    this.TaskIDField = value;
                    this.RaisePropertyChanged("TaskID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TaskType {
            get {
                return this.TaskTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskTypeField, value) != true)) {
                    this.TaskTypeField = value;
                    this.RaisePropertyChanged("TaskType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gams.com", ConfigurationName="TaskManager.TaskQueueSoap")]
    public interface TaskQueueSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gams.com/GetStatus", ReplyAction="*")]
        bool GetStatus();
        
        // CODEGEN: Generating message contract since element name sBotID from namespace http://gams.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gams.com/GetTask", ReplyAction="*")]
        Tier_3_Transport.TaskManager.GetTaskResponse GetTask(Tier_3_Transport.TaskManager.GetTaskRequest request);
        
        // CODEGEN: Generating message contract since element name sTaskID from namespace http://gams.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gams.com/SubmitResult", ReplyAction="*")]
        Tier_3_Transport.TaskManager.SubmitResultResponse SubmitResult(Tier_3_Transport.TaskManager.SubmitResultRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTask", Namespace="http://gams.com", Order=0)]
        public Tier_3_Transport.TaskManager.GetTaskRequestBody Body;
        
        public GetTaskRequest() {
        }
        
        public GetTaskRequest(Tier_3_Transport.TaskManager.GetTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gams.com")]
    public partial class GetTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sBotID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sTaskType;
        
        public GetTaskRequestBody() {
        }
        
        public GetTaskRequestBody(string sBotID, string sTaskType) {
            this.sBotID = sBotID;
            this.sTaskType = sTaskType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTaskResponse", Namespace="http://gams.com", Order=0)]
        public Tier_3_Transport.TaskManager.GetTaskResponseBody Body;
        
        public GetTaskResponse() {
        }
        
        public GetTaskResponse(Tier_3_Transport.TaskManager.GetTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gams.com")]
    public partial class GetTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tier_3_Transport.TaskManager.TaskDetails GetTaskResult;
        
        public GetTaskResponseBody() {
        }
        
        public GetTaskResponseBody(Tier_3_Transport.TaskManager.TaskDetails GetTaskResult) {
            this.GetTaskResult = GetTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitResult", Namespace="http://gams.com", Order=0)]
        public Tier_3_Transport.TaskManager.SubmitResultRequestBody Body;
        
        public SubmitResultRequest() {
        }
        
        public SubmitResultRequest(Tier_3_Transport.TaskManager.SubmitResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gams.com")]
    public partial class SubmitResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sTaskID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sOutputValues;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sLogs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sStatus;
        
        public SubmitResultRequestBody() {
        }
        
        public SubmitResultRequestBody(string sTaskID, string sOutputValues, string sLogs, string sStatus) {
            this.sTaskID = sTaskID;
            this.sOutputValues = sOutputValues;
            this.sLogs = sLogs;
            this.sStatus = sStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitResultResponse", Namespace="http://gams.com", Order=0)]
        public Tier_3_Transport.TaskManager.SubmitResultResponseBody Body;
        
        public SubmitResultResponse() {
        }
        
        public SubmitResultResponse(Tier_3_Transport.TaskManager.SubmitResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SubmitResultResponseBody {
        
        public SubmitResultResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TaskQueueSoapChannel : Tier_3_Transport.TaskManager.TaskQueueSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaskQueueSoapClient : System.ServiceModel.ClientBase<Tier_3_Transport.TaskManager.TaskQueueSoap>, Tier_3_Transport.TaskManager.TaskQueueSoap {
        
        public TaskQueueSoapClient() {
        }
        
        public TaskQueueSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaskQueueSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskQueueSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskQueueSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetStatus() {
            return base.Channel.GetStatus();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tier_3_Transport.TaskManager.GetTaskResponse Tier_3_Transport.TaskManager.TaskQueueSoap.GetTask(Tier_3_Transport.TaskManager.GetTaskRequest request) {
            return base.Channel.GetTask(request);
        }
        
        public Tier_3_Transport.TaskManager.TaskDetails GetTask(string sBotID, string sTaskType) {
            Tier_3_Transport.TaskManager.GetTaskRequest inValue = new Tier_3_Transport.TaskManager.GetTaskRequest();
            inValue.Body = new Tier_3_Transport.TaskManager.GetTaskRequestBody();
            inValue.Body.sBotID = sBotID;
            inValue.Body.sTaskType = sTaskType;
            Tier_3_Transport.TaskManager.GetTaskResponse retVal = ((Tier_3_Transport.TaskManager.TaskQueueSoap)(this)).GetTask(inValue);
            return retVal.Body.GetTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tier_3_Transport.TaskManager.SubmitResultResponse Tier_3_Transport.TaskManager.TaskQueueSoap.SubmitResult(Tier_3_Transport.TaskManager.SubmitResultRequest request) {
            return base.Channel.SubmitResult(request);
        }
        
        public void SubmitResult(string sTaskID, string sOutputValues, string sLogs, string sStatus) {
            Tier_3_Transport.TaskManager.SubmitResultRequest inValue = new Tier_3_Transport.TaskManager.SubmitResultRequest();
            inValue.Body = new Tier_3_Transport.TaskManager.SubmitResultRequestBody();
            inValue.Body.sTaskID = sTaskID;
            inValue.Body.sOutputValues = sOutputValues;
            inValue.Body.sLogs = sLogs;
            inValue.Body.sStatus = sStatus;
            Tier_3_Transport.TaskManager.SubmitResultResponse retVal = ((Tier_3_Transport.TaskManager.TaskQueueSoap)(this)).SubmitResult(inValue);
        }
    }
}
